### ISSUE TITLE
Website docs is offline

### ISSUE THREAD

**Issue by BerkerSP** [Gokujo/telegramposting#1]
Здравствуйте, я пытаюсь получить доступ к документации, но сайт выдает ошибку. У меня проблемы с выражением названия, поля short-story и xfield, как я могу выразить это? Есть ли какой-нибудь пример, чтобы иметь четкую ссылку? Большое спасибо

**Comment by Gokujo** [comment]
https://devcraft.club/articles/telegram-posting.7/

У домена слетел SSL сертификат, я даже и не заметил. Обновил. Сайт снова доступен. Вся документация по модулю - по ссылке выше
