### ISSUE TITLE
Поддержка 14.1

### ISSUE THREAD

**Issue by galaxyartsua** [Gokujo/telegramposting#3]
Здравствуйте! При установке пишет, что есть поддержка только 15.1?

**Comment by Gokujo** [comment]
Работоспособность не проверялась на версиях DLE ниже 15.1
Откройте файл [install.xml](https://github.com/Gokujo/telegramposting/blob/master/upload/install.xml) и на 7ой строчке замените 15.1 на 14.1.

Будет работать - хорошо, а не будет - рекомендую обновить движок. И так времени мало на разработку, а поддерживать старые версии дле - затратно.

**Comment by Gokujo** [comment]
Если нет никаких вопросов - то я закрою тикет
